name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Tidy
      run: rebar3 update
           rebar3 lint
    - name: Format
      run: rebar3 steamroll
    - name: Run tests
      run: rebar3 do eunit, ct
